### ISSUE TITLE
Bring back german wordlist

### ISSUE THREAD

**Issue by dotcs** [martinhoefling/goxkcdpwgen#5]
In d48fd514 the support for the german language has been dropped because it contained racist terms. Can we do something to bring this feature back? I've shortly looked into the wordlist and found a couple of words that might have caused this issue, e.g. "neger" or "dorfjude". Could we maybe add a filter mechanism to the wordlist, so that we can ensure that certain words are not in the list (also not partially)? I don't know exactly where the words came from, but maybe already the upstream source has a possibility to filter certain words?

**Comment by svenXY** [comment]
I have found https://github.com/dys2p/wordlists-de which - at first sight - does not seem to include any of these terms

**Comment by dominikschulz** [comment]
https://github.com/dys2p/wordlists-de/blob/main/de-7776-v1.txt looks great at first sight. Would be great to get this back.
